### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by simonv3** [zulumarketing/xhtml2pdf#6]
Is there Python 3 support for this module? If so, maybe the readme should indicate so?

Related to: https://github.com/chrisglass/xhtml2pdf/issues/223

**Comment by r14c** [comment]
#4 might interest you.

Python 3 _does_ technically work, but there are a lot of issues left to tackle before I'd be comfortable officially supporting it. In short, we have Python 3 support for our specific use cases; anything outside of that is unknown to us.

If there are any specific Python 3 issues you need fixed I'd be happy to take a look them.

**Comment by simonv3** [comment]
Cool. I've used html2pdf (the kind of abandoned one) in the past. For my current project I'll be using Reportlab (it's more image drawing), but I'll keep this in mind. I can close this issue unless you think it'll be useful to other people.
